### PR TITLE
Add model to req object returned by get method

### PR DESCRIPTION
**Pull request by solidgoldpig**
## What Changed & Why

Adds model to the request object returned by the `get` method to bring it line with other methods.

Also adds tests that confirm correct model is added to other methods.

## Bug/Ticket Tracker

https://github.com/twg/devour/issues/216

### CODE REVIEW

**Comment by solidgoldpig** [comment]
Thanks @tijn and @auvipy .  Any idea when this will make it into a new release?

**Comment by khalid283** [comment]
@tijn release 2.1.1 has not pushed into npm.

**Comment by tijn** [comment]
@khalid283 oh, I'll see if I can quickly fix that. Thanks for the heads-up!

**Comment by tijn** [comment]
Oh, I obviously cannot since npmjs.com doesn't know me yet.

@Emerson or @Auspicus, seeing that you talked about this last year, could either of you perhaps grant me the rights to publish to npm? My username over there is tijn-jobport .

**Comment by khalid283** [comment]
@Emerson Please give npmjs.com access to @tijn

**Comment by Emerson** [comment]
Ok! Invited to NPM. Sorry for the delay 👍

**Comment by tijn** [comment]
@khalid283 yes. Done. (I hope 🤞) 

I had some trouble with the publish script because I wanted to publish from the right git tag because the master branch is newer than v2.1.1 and well, that delayed stuff.

**Comment by khalid283** [comment]
@tijn Thank you

**Pull request merged**
