### PR TITLE
Fix compatibility with fortune-json-api

### PR DESCRIPTION
**Pull request by zchrykng**
## Priority
I have it patched locally, but would like it patched upstream before using this anywhere else.

## What Changed & Why
- index.js - added GET middleware reference
- req-get.js - created GET middleware

### CODE REVIEW

**Comment by Emerson** [comment]
Thanks for catching this – just a small issue with formatting (we are using [standard](https://github.com/feross/standard)). Can you update your PR and remove the trailing spaces?

Thanks for the help! 💯

**Comment by zchrykng** [comment]
Ok. Should be fixed.

**Comment by Emerson** [comment]
👍

**Comment by zchrykng** [comment]
When would this be included in a published version?

Just checking to see how long I should be making sure I patch it myself.

**Comment by Emerson** [comment]
Just published `1.3.1` which includes this code 🎉

**Pull request merged**
