### PR TITLE
send truly empty bodies in GET and DELETE requests

### LINKED ISSUE #38: Send empty bodies on GET and DELETE
Since GET and DELETE are not required to have bodies per the JSON API spec, having even an empty JSON object for the body can cause some servers to not respond properly.

### PR DESCRIPTION
**Pull request by zchrykng**
Fixes #38

### CODE REVIEW

**Comment by zchrykng** [comment]
Sorry for all the pull requests. Figured it was a better idea to send small changes as I found bugs. :)

**Comment by zchrykng** [comment]
Any thought on this? If it is not something that is going to be patched I will just figure out another way to work around the issue.

**Comment by randym** [comment]
As a user of the module, this feels like the right thing to do, but I'd prefer that this change was covered in specs to ensure that it does not some how get added back in as a regression.

**Comment by Emerson** [comment]
^ agree with @randym – add a quick test and we'll merge this in ASAP

**Comment by zchrykng** [comment]
Thanks @randym & @Emerson. I will work on that. Might be able to do it today.

**Comment by zchrykng** [comment]
Would you create a unique test for this or add testing to the current tests. (I am kind of new to tests)

**Comment by zchrykng** [comment]
Ok. Should be all fixed now and rebased on current master.

**Comment by zchrykng** [comment]
@Emerson Any changes needed?

**Comment by Emerson** [comment]
Ah, sorry – merging now! thanks Zachary

**Comment by zchrykng** [comment]
Thanks! :+1:

**Comment by Emerson** [comment]
@zchrykng – just published, thanks again for the help!

**Pull request merged**
