### PR TITLE
Support relationship destroy

### PR DESCRIPTION
**Pull request by SirLamer**
## Priority
Priority: high

This package fails to comply with the JSON API spec by not allowing relationship records to be deleted at present.

## What Changed & Why
The destroy() method accepts either zero or two arguments. When destroying has-many relationship records, a list of relationship record objects ('type' and 'id') are required. This PR allows for this case.

## Testing
List step-by-step how to test the changes.
- [ ] Use destroy() in its current form as normal with two arguments to make sure it still works and compatibility is not broken
- [ ] Call destroy() on a has-one relationship to try to remove it
- [ ] Call destroy() with an array of relationship record objects on a has-many relationship

## Bug/Ticket Tracker
Related Issue: https://github.com/twg/devour/issues/55
Another PR I submitted which is closely related to this: https://github.com/twg/devour/pull/99

## Documentation
http://jsonapi.org/format/#crud-updating-relationships

## In Progress/Follow Up
A unit test is included, which relies on a hacky work-around of the absence of a "relationships()" chain method for the URL builder, a feature which my other PR linked above addresses. If the other PR is accepted, the unit test should be revised to not use the hacky trick.

This line:
```js
jsonApi.one('foo', 1).all('relationship').all('bar').destroy(payload).then(() => done()).catch(() => done())
```

Should be changed to this:
```js
jsonApi.one('foo', 1).relationships().all('bar').destroy(payload).then(() => done()).catch(() => done())
```

### CODE REVIEW

**Comment by Emerson** [comment]
Merged your `relationships()` PR so feel free to update that hacky test you referenced.

I'm a little out of practice with this code base, but since all the tests are passing I'm going to trust that this is all good _(anyone else feel free to chime in)_.

**Comment by SirLamer** [comment]
For what it's worth, complexity arises out of this API request method being the only one out of the set which can be used on its own as well as in a chain.

So, this is allowed:
```js
jsonApi.destroy('foo', 1)
```

And this:
```js
jsonApi.one('foo',1).destroy()
```

And now finally this:
```js
jsonApi.one.('foo',1).relationships().all('bar').destroy({type: "bars", id: "2"})
```

This use depends on counting the number of arguments provided to then infer which case applies. This simultaneously means that this request method is the only one in the batch which cannot accept meta data or parameters.

Replacing the first case above with an alternative would be simpler and more reliable and also would then follow the same pattern used for the other request types.

For example, this is not supported:
```js
jsonApi.get('foo', 1)
```

Instead you have this:
```js
jsonApi.find('foo', 1)
```

Or this:
```js
jsonApi.one('foo', 1).get()
```

A proposed alternative would be a "delete()" method for the request type calls, and keep destroy as the stand-alone action:
```js
jsonApi.one.('foo',1).relationships().all('bar').delete({type: "bars", id: "2"})
```

And this:
```js
jsonApi.one('foo',1).delete()
```

I like this pattern because then the method name matches the request type per typical RESTful patterns.

I did not affect this proposed change because it breaks compatibility so I felt you needed to make a call on this.

**Comment by SirLamer** [comment]
Okay I changed the destroy() test as requested.

**Comment by Emerson** [comment]
Hear you about the complexity, but it's something we're going to need to code around until at least `3.0`

**Pull request merged**
