### PR TITLE
Support in the url builder for trailing slashes.

### PR DESCRIPTION
**Pull request by raizyr**
## Priority
This PR is blocking my next action as I am trying to use the devour client to consume an API that uses trailing slashes for collection URLs.

## What Changed & Why
Added a constructor option in object form to optionally append trailing slashes to either/both collection and resource urls, and also an option to be passed to urlFor/buildUrl to accomplish the same thing without the knowledge of url type.

## Testing
List step-by-step how to test the changes.
- [ ] Run included tests

## Bug/Ticket Tracker
Discussed in #57 

## Legal/Security/Privacy
No known concerns.

## Third-Party
None added

## People
@Emerson @billxinli @spiderbites 

- Added constructor option to append trailing slashes to collection and resource urls separately.
- Added an option to urlFor to append a trailingSlash.
- Added an argument to buildUrl that will append the trailingSlash when `true` is passed.

### CODE REVIEW

**Comment by spiderbites** [comment]
Hi @raizyr thanks for putting the work in on this and apologies for taking a while to look at this.  I've made some changes here: https://github.com/twg/devour/commit/5892571a13c8fb0aca99eaf3d6ce53024310c1af

I wanted to remove the separate slash argument for `buildUrl` and have the slash settings just set in the constructor.  I've also paired down the tests a bit.

If this would satisfy your use case I'll go ahead a close your PR and re-open one from the devour branch.

Cheers

**Comment by raizyr** [comment]
The changes in 5892571a13c8fb0aca99eaf3d6ce53024310c1af seem to restrict slashes to all or nothing.  This would make it difficult to use `devour` for existing APIs where a combination is used, ie. slashes on collection URIs and no slashes on single resource URIs.

**Comment by spiderbites** [comment]
Nope, it keeps that functionality in there.  See an example in the tests here: https://github.com/twg/devour/commit/5892571a13c8fb0aca99eaf3d6ce53024310c1af#diff-3f6a2558d91eece0e6bb598535c20778R229

**Comment by raizyr** [comment]
Yeah, sorry, I scanned right past it the first time I looked.  This should work for my use case as well as any others I can think of at the moment. Thanks!

**Pull request closed without merging**
